# Generated by Django 4.2.7 on 2023-11-02 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatch',
            name='team1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='tournament.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammatch',
            name='team2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='tournament.team'),
            preserve_default=False,
        ),
    ]
