# Generated by Django 4.2.7 on 2023-11-02 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_remove_match_team1_remove_match_team2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1', to='tournament.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2', to='tournament.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_won', to='tournament.team'),
        ),
    ]
