# Generated by Django 4.2.7 on 2023-11-02 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_match_team1_match_team2_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='runnerup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_lost', to='tournament.team'),
        ),
    ]
